language: node_js
sudo: false
node_js:
  - "7.2"
  - "6.9"
  - "6.7"
  - "6.4"
  - "6.3.1"
  - "6.2"
  - "6.1"
  - "6.0"
  - "5.12"
  - "5.7"
  - "5.1"
  - "5.0"
  - "4.6"
  - "4.5"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
